### ISSUE TITLE
Question about the observation order in SMAC

### ISSUE THREAD

**Issue by LiZhYun** [tjuHaoXiaotian/pymarl3#3]
If I'm not wrong, the observation order in SMAC is fixed. So why do PI and PE work?

**Comment by tjuHaoXiaotian** [comment]
Hi，直接用中文回复你了哈！虽然feature已经按entity id的顺序排列好了，但存在同质实体的场景，还是天然存在信息冗余。举个简单的例子，下象棋的时候，在一个episode内或者不同episode之间，俩“马”所在的位置恰好可能会发生交换，但obs是不一样的：[马1（位置1），马2（位置2）] -> [马1（位置2），马2（位置1）]
