### ISSUE TITLE
Code for HPN-MAPPO

### ISSUE THREAD

**Issue by testMonkey02** [tjuHaoXiaotian/pymarl3#5]
Would u please provide the code for HPN-MAPPO? I want to try it to solve problems in wireless communications.
Thanks and regards.

**Comment by tjuHaoXiaotian** [comment]
Hello, we modified HPN-MAPPO based on the official code base (here: https://github.com/marlbenchmark/on-policy), which is very different from pymarl. During the experiment, we found that MAPPO was a bit difficult to adjust parameters and the performance was not very stable, so we did not merge it here.

Later I will include MAPPO and HPN-MAPPO implemented based on pymarl. If you are interested, you can also modify it based on pymarl3~
