### ISSUE TITLE
师兄好，我对于论文中的finetuned-qmix的数据有一些疑问

### ISSUE THREAD

**Issue by Rorschach2333** [tjuHaoXiaotian/pymarl3#6]
官方结果显示finetuned-qmix的数据如图，但是我看论文中的配图在这几个场景中貌似数据有些差异，如5m-vs_6m，文中曲线貌似在0.75左右。这个胜率的统计是怎么得出的呢，是因为曲线图做了平滑处理吗，实际胜率直接取最大胜率？
![b2a1061b076315ece150bf7d031611a](https://github.com/tjuHaoXiaotian/pymarl3/assets/91132024/fcaa9215-94dc-48b8-8d7b-c1450d160e68)

**Comment by Rorschach2333** [comment]
感谢师兄的优秀工作，启发良多

**Comment by tjuHaoXiaotian** [comment]
> 官方结果显示finetuned-qmix的数据如图，但是我看论文中的配图在这几个场景中貌似数据有些差异，如5m-vs_6m，文中曲线貌似在0.75左右。这个胜率的统计是怎么得出的呢，是因为曲线图做了平滑处理吗，实际胜率直接取最大胜率？ ![b2a1061b076315ece150bf7d031611a](https://private-user-images.githubusercontent.com/91132024/295085854-fcaa9215-94dc-48b8-8d7b-c1450d160e68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3Njg5NjksIm5iZiI6MTcwNDc2ODY2OSwicGF0aCI6Ii85MTEzMjAyNC8yOTUwODU4NTQtZmNhYTkyMTUtOTRkYy00OGI4LThkN2ItYzE0NTBkMTYwZTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAyNTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3OTViMWJmMjM5ZGZmMDcxMDc2YzRiN2U0YzZmNjM4YjBmYzBhY2M5YzQ4Nzc0YjUzMjE1MmQwNzQ3NDMzOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TLEr1C86SNu7BBMFU4P7svgRBXJRnJPKQ69fKdySygQ)

您好哈！感谢关注。论文里finetuned-qmix的结果就是按照README.md 4.2节的脚本跑出来的，参数比较统一（也是按照 finetuned-qmix官方论文推荐的参数）。5m_vs_6m胜率确实是在80%左右，我这边也没有跑出过90%，我猜可能是finetuned-qmix论文里report的结果是针对不同地图做超参搜索后得出的最优胜率。
