### ISSUE TITLE
关于HPN-MAPPO的问题

### ISSUE THREAD

**Issue by hj5717** [tjuHaoXiaotian/pymarl3#7]
老师您好，请问HPN-MAPPO是不是没有开源在库里呢？

**Comment by tjuHaoXiaotian** [comment]
您好，是的哈，HPN-MAPPO我们是基于官方代码库[https://github.com/marlbenchmark/on-policy]改的，跟pymarl两个版本代码库差异很大，而且实验的时候发现MAPPO有点不好调参，就没合并到这里来。

后面我会把基于pymarl实现的MAPPO和HPN-MAPPO放进来，您要感兴趣也可以基于pymarl3改一下~

**Comment by hj5717** [comment]
好的 谢谢老师的解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月20日(周六) 中午11:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tjuHaoXiaotian/pymarl3] 关于HPN-MAPPO的问题 (Issue #7)




 
您好，是的哈，HPN-MAPPO我们是基于官方代码库（这里：https://github.com/marlbenchmark/on-policy）改的，跟pymarl两个版本代码库差异很大，而且实验的时候发现MAPPO有点不好调参，就没合并到这里来。
 
后面我会把基于pymarl实现的MAPPO和HPN-MAPPO放进来，您要感兴趣也可以基于pymarl3改一下~

**Comment by hj5717** [comment]
> 

老师您好，如果把HPN用于自己的环境，是不是需要重写一个mac控制器呢
